### PR TITLE
Update style; add missing metadata

### PR DESCRIPTION
**Pull request by peterjc**
Removed the ``preserve_egg_dir`` setting as per discussion here (usage here dates back to the initial check in, so I assume it was following a then current recipe):
https://github.com/conda-forge/staged-recipes/issues/3056

Updated the installation command to follow current recommendations, now using pip (which I hope will fix the metadata issue I ran into with pip not seeing the conda package):
http://conda-forge.org/docs/maintainer/adding_pkgs.html#use-pip

Adding missing description and URL fields to metadata. Should look better here:
https://anaconda.org/conda-forge/python-levenshtein

Checklist
* [X] Used a fork of the feedstock to propose changes
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by peterjc** [comment]
@conda-forge-admin, please rerender

**Comment by peterjc** [comment]
@conda-forge/core  looks like various 404 errors including from https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py

Note sure what's up here, there is no branch 2.0 on https://github.com/conda-forge/conda-forge-ci-setup-feedstock

**Comment by scopatz** [comment]
@conda-forge-admin, please rerender

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by peterjc** [comment]
It seems like an infrastructure problem of some kind rather than down to the recipe itself, but is there anything I can do here?

**Comment by jakirkham** [comment]
We updated conda-smithy very recently. So that might be why the re-render failed. Trying again.

@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
@peterjc, if you can keep an eye on the CI statuses now that this has been re-rendered and let us know what happens, that would be great.

Suspect the CI configuration here was pretty old, which may be causing failures here. Though there could be other issues we haven't identified yet. Let's wait and see though. 🙂

**Comment by peterjc** [comment]
All green 👍

**Comment by jakirkham** [comment]
Great! Please feel free to merge 😄

**Comment by peterjc** [comment]
I don't have permissions to merge this myself.

**Comment by jakirkham** [comment]
Would you like to add yourself as a maintainer? If so, I'll happily merge now. If not, we can ping the maintainer team here and see if they can review.

**Comment by peterjc** [comment]
Adding self as a maintainer as suggested.

Also adding a trivial test that can call the compiled C code from Python.

**Comment by peterjc** [comment]
Hmm, the new simple test failed... should it avoid using ``{{ PYTHON }}``?

**Comment by jakirkham** [comment]
@conda-forge-admin, please re-render.

**Comment by jakirkham** [comment]
Thanks @peterjc! 😄

**Comment by jakirkham** [comment]
> Hmm, the new simple test failed... should it avoid using `{{ PYTHON }}`?

This is probably referring to the Python interpreter in the host environment during the build, which is non-existent in the test phase.

**Pull request merged**
