### PR TITLE
add maintainer

### PR DESCRIPTION
**Pull request by maxbachmann**
I am maintaining python-Levenshtein on pypi

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by peterjc** [comment]
I'm happy about this, but I think we'd need to bump the build number to merge this.

(Or include your name as part of the other currently open PR to update the package, but that's failing right now)

**Comment by peterjc** [comment]
Also we could change the URL to https://github.com/maxbachmann/python-Levenshtein is that is official now (pointed to from PyPI so I guess it is)?

What would you suggest for the documentation link? Is there a page about the module renaming and how to update?

**Comment by peterjc** [comment]
In fact, maybe this PR can handle the version update since #25 needs work to account for the fact PyPY now points to https://github.com/maxbachmann/python-Levenshtein which is a thin wrapper around a different Python package...

i.e. https://github.com/conda-forge/levenshtein-feedstock/

**Comment by maxbachmann** [comment]
> I'm happy about this, but I think we'd need to bump the build number to merge this.

I think without bumping the version number it is simply not going to upload the package again

> In fact, maybe this PR can handle the version update since https://github.com/conda-forge/python-levenshtein-feedstock/pull/25 needs work to account for the fact PyPY now points to https://github.com/maxbachmann/python-Levenshtein which is a thin wrapper around a different Python package...

Yes the need for this work is why I wanted to add myself as maintainer

> What would you suggest for the documentation link?

https://maxbachmann.github.io/Levenshtein/

> Is there a page about the module renaming and how to update?

For users generally things stay the same, since the project was always installed as `python-Levenshtein`, but then used as `Levenshtein`. So I think the simplest change would be to make python-Levenshtein a pure Python package which simply lists `Levenshtein` as dependency. The only complexity is that this breaks automatic updates, since we probably want to hardcode the dependency version on each update (e.g. v0.20.4 requires v0.20.4 of Levenshtein so installs can be used interchangeably)

**Comment by peterjc** [comment]
I've not found a good example of a conda metapackage, wrapping the PyPI metapackage might be enough (i.e. the work on #25 - I think we can handle pinning the matching dependency version there).

**Pull request closed without merging**
